myproject/authentication/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('<int:user_id>/', views.profile_view, name='profile'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('authentication/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

myproject/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

myproject/authentication/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import User
from django.urls import reverse

def login_view(request):
    if request.user.is_authenticated:
        return render(request, 'redirect.html',
         {
         'link': reverse('authentication:profile', args=(request.user.id,)),
         'text': 'Ya estas logueado, ir tu perfil:'})

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('authentication:profile', args=(user.id,)))
        else:
            return render(request, 'authentication/login.html', {'error_msg': 'datos incorrectos'})
    else:
        return render(request, 'authentication/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('authentication:login'))

def signup_view(request):
    if request.user.is_authenticated:
        return render(request, 'redirect.html',
         {
         'link': reverse('authentication:profile', args=(request.user.id,)),
         'text': 'Ya estas logueado, ir tu perfil:'})

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        try:
            u = User.objects.create_user(username=username, email=email, password=password)
            u.save()
        except:
            return render(request, 'authentication/signup.html',
             {'error_msg': 'No es posible crear cuenta con esos datos'})
        return HttpResponseRedirect(reverse('authentication:login'))
    else:
        return render(request, 'authentication/signup.html', {})

@login_required(login_url='authentication:login')
def profile_view(request, user_id):
    if user_id !=request.user.id:
        return HttpResponse('Acceso denegado!')

    u = User.objects.get(id=user_id)
    name = u.username
    return render(request, 'authentication/profile.html', {'username': name})

myproject/myproject/views.py
from django.shortcuts import render

def base_view(request):
    return render(request, 'base.html', {hola: 'hola'})

myproject/authentication/templates/authentication/login.html
<head>
    <title>Invest Simulator</title>
</head>

<h1>Login </h1>

{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

<form action="{% url 'authentication:login' %}" method="post">
{% csrf_token %}
  <p>Nombre de usuario: <input type="text" name="username" placeholder="username" /></p>
  <p>Contraseña: <input type="password" name="password" placeholder="password" /></p>
  <button type="submit" class="btn">Login</button>
</form>

<p>No tenés cuenta? Registrate <a href="{% url 'authentication:signup' %}">acá!</a></p>

myproject/authentication/templates/authentication/profile.html
{% extends 'base.html' %}

{% block content %}
<p> Hola {{username}}!<p/>
{% endblock content %}

myproject/authentication/templates/authentication/signup.html
<head>
    <title>Invest Simulator</title>
</head>

<h1>Sign Up </h1>

{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

<form action="{% url 'authentication:signup' %}" method="post">
{% csrf_token %}
  <p>Nombre de usuario: <input type="text" name="username" placeholder="username" /><p/>
  <p>Email: <input type="text" name="email" placeholder="email" /><p/>
  <p>Contraseña: <input type="password" name="password" placeholder="password" /><p/>
  <button type="submit" class="btn">Sign up</button>
</form>

<p>Ya tenés cuenta? Logueate <a href="{% url 'authentication:login' %}">acá!</a><p/>

myproject/myproject/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Invest Simulator</title>
    </head>

    <p><a href="{% url 'authentication:logout' %}">Log out</a></p>

    <hr>

    <body>
      {% block content %}{% endblock content %}
    </body>
</html>

myproject/myproject/templates/redirect.html
<!DOCTYPE html>
<html>
    <head>
        <title>Invest Simulator</title>
    </head>
    <p>{{ text }}</p>
    <p><a href="{{ link }}">Ir!</a></p>

</html>